### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by flamoedo** [metaschema/firebase-oxygen#1]
Hi,

I'm trying to use the demo, but is not working.
I'm looking for a full text search to use on a android app.

**Comment by hidekiyamamoto** [comment]
wow.. I am so sorry
we are working on a much friendly version you can see at app.htm

are you using it via YOUR database
or via our demo database?

**Comment by hidekiyamamoto** [comment]
I can see....
It's infact broken...
I 'll fix the console.htm right now!

While you wait you may prefer the release 0.1 alpha that is stored in github
- it's really "UGLY" but working.

**Comment by hidekiyamamoto** [comment]
...btw this entirely new approach of directly using firebase is days new in
our minds and we just started... if you are searching for a production
solution - for now - you should rely on elasticsearch + firebase as stated
in the firebase blog.

**Comment by hidekiyamamoto** [comment]
ok the index dosn't work for word shorter than two characters!!!!!

**Comment by hidekiyamamoto** [comment]
open http://rawgit.com/hidekiyamamoto/firebase-oxygen/master/app.html
and search for ddd in the text field
or other words that make up the tag trre you can build on your left...
(drag and drop for creating a new node)
