### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by appodeepa** [metaschema/firebase-oxygen#2]
Hi! Wondering how to get started using this.

**Comment by hidekiyamamoto** [comment]
So sorry for late reply.... a quickstart guide will be competed  for the
end of september...

If you are medium/advanced lets say you only need to use f$.db.add for
inserts and f$.db.set for updating documents in the db.

If you do this the contents get indexed.
For reads you could use normal firbase api.

For searching in the index use the f$.db.find function.
Il 21/Ago/2016 09:43 AM, "Mike" notifications@github.com ha scritto:

**Comment by hidekiyamamoto** [comment]
The library basic test form is more or less working, even is some examples are missing.
