### ISSUE TITLE
How Do I use this?

### ISSUE THREAD

**Issue by crearo** [metaschema/firebase-oxygen#3]
This looks promising, but I really don't have a clue of how to use this.

Any usable documentation? Do I have to create a separate server for the same?

**Comment by hidekiyamamoto** [comment]
BAsically the searching feature is made available thanks to the oxyzen
library.

It means, instead of doing push and set via firebase api, you do it using
oxyzen api.

If you insert and update using oxyzen api, while insterting and updating,
the code also creates an index in the firebase datase, that can be used to
search using oxyzen search funcion

**Comment by hidekiyamamoto** [comment]
The files ONLINe in git hub aren't very updated.... we are now going
forward with the code using a small project we had, in a few days we'll be
onine, then we'll merge in the onine public demo all the updates

**Comment by hidekiyamamoto** [comment]
this is all clientside.... i had it working for a project with about 100000
interlinked records in 5 different collections
It is working , with excelent performances, if we compare to the same db
accessed via aspx or php server code, firebase + clientside is BETTER.

**Comment by hidekiyamamoto** [comment]
No externa server...
i am sorry we are very busisy with other projects...
eoi.metaschema.io

This web site is just static files AND firbase
we admin it using metaschema +oxygen
via eoi.metaschema.io/admin

but of course it's private db, so it's not demoable  by you...
just give some small days, or give more detailed questions...

On Tue, Oct 25, 2016 at 10:16 AM, Rishabh Bhardwaj <notifications@github.com

**Comment by hidekiyamamoto** [comment]
The library basic test form is more or less working, even is some examples are missing.
